
# HE2: Consultoría e IA responsable  
## Semana 1: Fundamentos de Python con **pandas** (indexación y filtrado)

**Autor:** *Catalina Bernal y Santiago Neira*  
**Semestre:** 2026-2  


---

### Propósitos de la clase
- Repasar **objetos y tipos** de Python.
- Practicar **listas**, **tuplas**, **diccionarios** y **conjuntos**.
- Revisar **control de flujo** (`if/elif/else`) y **bucles** (`for`, `range`, `enumerate`, *list comprehensions*).
- Introducir **pandas** **después** del repaso anterior, enfocándonos **solo** en:
  - Exploración básica: `head`, `tail`, `shape`, `columns`, `dtypes`, `info`, `describe`.
  - **Indexación simple** y **filtrado simple**: `df["col"]`, `df[["col1","col2"]]`, `.loc`, `.iloc` y filtros booleanos básicos.



## Temas de la sesión
1. Objetos y tipos en Python - Repaso de programación en python.  
2. Estructuras: listas, tuplas, diccionarios, conjuntos.  
3. Control de flujo y bucles.  
4. **pandas**: instalación/importación, creación de DataFrame ficticio, exploración, **indexación simple** y **filtrado simple**.  
5. **Ejercicios de cierre**.



---

## 1) Repaso: **Objetos y tipos**


In [1]:

# Números, texto, booleanos y None
a = 7            # int
b = 2.5          # float
c = a + b
print(a, type(a))
print(b, type(b))
print(c, type(c))

7 <class 'int'>
2.5 <class 'float'>
9.5 <class 'float'>


In [1]:
texto = "ECON 3532"  # str
flag = True      # bool
nada = None      # NoneType
print(texto, type(texto))
print(flag, type(flag))
print(nada, type(nada))

ECON 3532 <class 'str'>
True <class 'bool'>
None <class 'NoneType'>


In [4]:
## Operaciones
a = 7            # int
b = 2.5          # float
c = a + b
print(a+b)
print(a*b)
print(texto*2)
print(texto + ": Así es el código del curso")
print(a%2)

9.5
17.5
ECON 3532ECON 3532
ECON 3532: Así es el código del curso
1


In [5]:
# Asignaciones 
a = 7            # int
b = 2.5          # float
c = a + b
print(a)
a+=1
print(a)

7
8



---

## 2) **Listas**, **tuplas**, **diccionarios**, **conjuntos**


In [7]:
# Listas
nums = [1, 2, 3]

In [8]:
##Indexación 
nums[2]

3

In [9]:
nums[-1]

3

In [11]:
##Manipulación
#Añadiendo elementos
print("Lista antes de adición de elemento ", nums)
nums.append(4)
print("Lista después de adición de elemento ", nums)


Lista antes de adición de elemento  [1, 2, 3, 4]
Lista después de adición de elemento  [1, 2, 3, 4, 4]


In [12]:
#Cambiando elementos
nums[0] = 10
print("Lista:", nums)

Lista: [10, 2, 3, 4, 4]


In [13]:

# Tuplas (inmutables)
t = (10, 20, 30)
print("Tupla:", t)


Tupla: (10, 20, 30)


In [14]:
# Podemos indexar las tuplas! Pero no podemos transformarlas
t[2]

30

In [23]:
t[2]
t[2] = 20

TypeError: 'tuple' object does not support item assignment

In [20]:
# Diccionarios
estudiante = {"nombre": "Ana", "edad": 19, "programa": "Economía"}
## Podemos indexar? Sí, a través de los nombres de las llaves.
estudiante["nombre"]



'Ana'

In [21]:
estudiante["edad"] += 1

In [22]:

print("Diccionario:", estudiante)

Diccionario: {'nombre': 'Ana', 'edad': 20, 'programa': 'Economía'}


In [24]:


# Conjuntos (sin duplicados)
A = {1, 2, 3}
B = {3, 4, 5}
print("Unión:", A | B)
print("Intersección:", A & B)
print("Diferencia:", A - B)

Unión: {1, 2, 3, 4, 5}
Intersección: {3}
Diferencia: {1, 2}



---

## 3) **Control de flujo** y **bucles**


In [25]:

# if / elif / else
x = 17
if x % 2 == 0:
    print("par")
elif x % 3 == 0:
    print("divisible por 3")
else:
    print("otro")




otro


In [26]:
### Accediendo a los elementos de una lista
for i in nums:
    print(i)

10
2
3
4
4


In [27]:
# for + range 
suma = 0
for i in range(1, 6):  # 1..5
    suma += i
print("Suma 1..5 =", suma)


Suma 1..5 = 15


In [28]:
# For loop con enumerate, accedemos al índice y al elemento
frutas = ["manzana", "pera", "banano"]
for idx, f in enumerate(frutas):
    print(idx, f)


0 manzana
1 pera
2 banano


In [29]:
# list comprehension
impares_cuadrados = [i*i for i in range(1, 16) if i % 2 == 1]
print("Impares^2:", impares_cuadrados)

Impares^2: [1, 9, 25, 49, 81, 121, 169, 225]



---

## 4) **pandas** 

### 4.1 Instalación 


In [30]:

# pip (Jupyter)
# Descomenta y ejecuta si necesitas instalar
# !pip install --upgrade pip
# !pip install pandas



### 4.2 Importación


In [31]:

import pandas as pd
print("pandas:", pd.__version__)


pandas: 3.0.0



### 4.3 Crear un **DataFrame ficticio**
Incluimos algunos valores faltantes para ver cómo lucen en pantalla (sin tratarlos hoy).


In [32]:

df = pd.DataFrame({
    "tienda":   ["A","A","B","B","C","C","C","D","D","D"],
    "mes":      ["2025-01","2025-02","2025-01","2025-02","2025-01","2025-02","2025-03","2025-01","2025-02","2025-03"],
    "ventas":   [120, 150, 80, 130, 90, 110, None, 160, 170, 180],
    "unidades": [12, 14, 9, 13, 8, 10,  9,    None, 16, 18],
    "categoria":["Electro","Electro","Hogar","Hogar","Electro","Hogar","Hogar","Hogar","Electro","Electro"]
})
df.head()


tienda      mes  ventas  unidades categoria
0      A  2025-01   120.0      12.0   Electro
1      A  2025-02   150.0      14.0   Electro
2      B  2025-01    80.0       9.0     Hogar
3      B  2025-02   130.0      13.0     Hogar
4      C  2025-01    90.0       8.0   Electro


### 4.4 Exploración básica
- `head`, `tail`  
- `shape`, `columns`, `dtypes`  
- `info()` y `describe()`


In [33]:
df.head(10)      # primeras filas

tienda      mes  ventas  unidades categoria
0      A  2025-01   120.0      12.0   Electro
1      A  2025-02   150.0      14.0   Electro
2      B  2025-01    80.0       9.0     Hogar
3      B  2025-02   130.0      13.0     Hogar
4      C  2025-01    90.0       8.0   Electro
5      C  2025-02   110.0      10.0     Hogar
6      C  2025-03     NaN       9.0     Hogar
7      D  2025-01   160.0       NaN     Hogar
8      D  2025-02   170.0      16.0   Electro
9      D  2025-03   180.0      18.0   Electro

In [34]:
df.tail(2)     # últimas filas

tienda      mes  ventas  unidades categoria
8      D  2025-02   170.0      16.0   Electro
9      D  2025-03   180.0      18.0   Electro

In [35]:
df.shape        # (filas, columnas)

(10, 5)

In [36]:
df.columns      # nombres de columnas

Index(['tienda', 'mes', 'ventas', 'unidades', 'categoria'], dtype='str')

In [37]:
df.dtypes       # tipos por columna

tienda           str
mes              str
ventas       float64
unidades     float64
categoria        str
dtype: object

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   tienda     10 non-null     str    
 1   mes        10 non-null     str    
 2   ventas     9 non-null      float64
 3   unidades   9 non-null      float64
 4   categoria  10 non-null     str    
dtypes: float64(2), str(3)
memory usage: 532.0 bytes


In [39]:
df.describe()

ventas   unidades
count    9.000000   9.000000
mean   132.222222  12.111111
std     35.276684   3.443996
min     80.000000   8.000000
25%    110.000000   9.000000
50%    130.000000  12.000000
75%    160.000000  14.000000
max    180.000000  18.000000


### 4.5 **Indexación simple** y **filtrado simple**
- Columnas: `df["col"]`, `df[["col1","col2"]]`  
- Filtrado básico (una o dos condiciones simples):  
  - `df[df["tienda"] == "A"]`  
  - `df[(df["tienda"] == "A") & (df["mes"] == "2025-02")]`  
- `.loc` (por **etiquetas**) y `.iloc` (por **posición**) para filas/columnas.


In [40]:

# Selección por columnas
ventas = df["ventas"]
ventas.head()


0    120.0
1    150.0
2     80.0
3    130.0
4     90.0
Name: ventas, dtype: float64

In [41]:
## Seleccionando varias columnas por nombre
subset = df[["tienda", "ventas"]]
subset.head()

tienda  ventas
0      A   120.0
1      A   150.0
2      B    80.0
3      B   130.0
4      C    90.0

In [42]:
### Creación de columnas.
df_prueba= df.copy()
df_prueba["Número fijo"]=2
df_prueba.head()

tienda      mes  ventas  unidades categoria  Número fijo
0      A  2025-01   120.0      12.0   Electro            2
1      A  2025-02   150.0      14.0   Electro            2
2      B  2025-01    80.0       9.0     Hogar            2
3      B  2025-02   130.0      13.0     Hogar            2
4      C  2025-01    90.0       8.0   Electro            2

In [43]:
## Podemos crear columnas a partir de columnas ya existentes?
df_prueba["ventas_cuadrado"]=df_prueba["ventas"]**2
df_prueba.head()

tienda      mes  ventas  unidades categoria  Número fijo  ventas_cuadrado
0      A  2025-01   120.0      12.0   Electro            2          14400.0
1      A  2025-02   150.0      14.0   Electro            2          22500.0
2      B  2025-01    80.0       9.0     Hogar            2           6400.0
3      B  2025-02   130.0      13.0     Hogar            2          16900.0
4      C  2025-01    90.0       8.0   Electro            2           8100.0

In [44]:
# Filtrado básico (condiciones simples)
solo_A = df[df["tienda"] == "A"]
solo_A


tienda      mes  ventas  unidades categoria
0      A  2025-01   120.0      12.0   Electro
1      A  2025-02   150.0      14.0   Electro

In [45]:
B_feb = df[(df["tienda"] == "B") & (df["mes"] == "2025-02")]
B_feb

tienda      mes  ventas  unidades categoria
3      B  2025-02   130.0      13.0     Hogar

In [46]:

# .loc: por etiquetas (filas y columnas)
febrero_cols = df.loc[df["mes"] == "2025-02", ["tienda","mes","ventas"]]
febrero_cols.head()


tienda      mes  ventas
1      A  2025-02   150.0
3      B  2025-02   130.0
5      C  2025-02   110.0
8      D  2025-02   170.0

In [47]:
# .iloc: por posición (slicing simple)
primeras_filas = df.iloc[0:5, :]   # primeras 5 filas, todas las columnas
primeras_filas

tienda      mes  ventas  unidades categoria
0      A  2025-01   120.0      12.0   Electro
1      A  2025-02   150.0      14.0   Electro
2      B  2025-01    80.0       9.0     Hogar
3      B  2025-02   130.0      13.0     Hogar
4      C  2025-01    90.0       8.0   Electro

In [48]:
algunas_cols = df.iloc[:, 0:3]     # todas las filas, 3 primeras columnas
algunas_cols


tienda      mes  ventas
0      A  2025-01   120.0
1      A  2025-02   150.0
2      B  2025-01    80.0
3      B  2025-02   130.0
4      C  2025-01    90.0
5      C  2025-02   110.0
6      C  2025-03     NaN
7      D  2025-01   160.0
8      D  2025-02   170.0
9      D  2025-03   180.0

In [49]:
casos_especificos = df.iloc[1:4,1:3]
casos_especificos

mes  ventas
1  2025-02   150.0
2  2025-01    80.0
3  2025-02   130.0


---

## 5) 🧩 **Ejercicios de cierre** (enfocados en indexación ,filtrado y construcción de variables. )

1. Obtén únicamente las columnas `["tienda", "mes"]` del DataFrame.  
2. Filtra las filas donde `tienda == "C"`.  
3. Filtra las filas donde `ventas >= 120`. (Considera que hay `NaN` en `ventas`.)  
4. Usa `.loc` para quedarte con las filas de `"2025-02"` y solo las columnas `["tienda","ventas"]`.  
5. Usa `.iloc` para:  
   a) Obtener las primeras 4 filas y las 2 primeras columnas.  
   b) Obtener de la fila 3 a la 6 (sin incluir 6), todas las columnas.
6. Construye una columna en la base `df_prueba` que sea un condicional. Si hay más de 110 en ventas que sea verdadero, y falso de lo contrario.

> Pista: recuerda `df["col"]`, `df[["c1","c2"]]`, comparaciones (`==`, `>=`), operadores `&`/`|`, `.loc` y `.iloc`.


In [ ]:

# Escribe tus soluciones aquí

# 1) 
import pandas as pd
print("pandas:", pd.__version__)
df = pd.DataFrame({
    "tienda":   ["A","A","B","B","C","C","C","D","D","D"],
    "mes":      ["2025-01","2025-02","2025-01","2025-02","2025-01","2025-02","2025-03","2025-01","2025-02","2025-03"],
    "ventas":   [120, 150, 80, 130, 90, 110, None, 160, 170, 180],
    "unidades": [12, 14, 9, 13, 8, 10,  9,    None, 16, 18],
    "categoria":["Electro","Electro","Hogar","Hogar","Electro","Hogar","Hogar","Hogar","Electro","Electro"]
})
subset = df[["tienda", "mes"]]

# 2)
solo_C = df[df["tienda"] == "C"]
solo_C

# 3)
solo_120 = df[(df["ventas"] >= 120)]
solo_120 

# 4)
febrero_cols = df.loc[df["mes"] == "2025-02", ["tienda","ventas"]]
febrero_cols.head()

# 5a)
orden_filas = df.iloc[0:4, 0:2]
orden_filas

# 5b)
orden2_filas = df.iloc[3:5, :]
orden2_filas

# 6)
df["ventas2"] = df["ventas"] >= 110
df




pandas: 3.0.0


tienda      mes  ventas  unidades categoria  ventas2
0      A  2025-01   120.0      12.0   Electro     True
1      A  2025-02   150.0      14.0   Electro     True
2      B  2025-01    80.0       9.0     Hogar    False
3      B  2025-02   130.0      13.0     Hogar     True
4      C  2025-01    90.0       8.0   Electro    False
5      C  2025-02   110.0      10.0     Hogar     True
6      C  2025-03     NaN       9.0     Hogar    False
7      D  2025-01   160.0       NaN     Hogar     True
8      D  2025-02   170.0      16.0   Electro     True
9      D  2025-03   180.0      18.0   Electro     True